# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c0be61555f6e7ed333ffc253a13817b14bf51070239d03900095376ba0d0a4b423fd48920a339c8857c967739d82f6370371e43c7318663839b201e7515821a6

test:
  secret_key_base: 51dfb6ce07390e60a88d91ae3d1ee8e821856e44cd18c925c899cc0583f547f264c5061f1e38a32acc616c4d3d240d48f02d368896c4118b48070b19375f2bb4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
